# Generated by Django 4.2.15 on 2024-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=150),
        ),
    ]
