# Generated by Django 4.2.15 on 2024-08-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/default_profile_pic.jpg",
                upload_to="profile_pics/",
            ),
        ),
    ]
