# Generated by Django 4.2.15 on 2024-10-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0004_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
