# Generated by Django 4.2.15 on 2024-10-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0006_user_email_verified_user_token_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="status",
            field=models.CharField(default="pending", max_length=10),
        ),
    ]
